In [ ]:
name.py --> import name

In [ ]:
import name
import name as whatever_sentence_you_want
from name import variable_1, function_name, class_name, whatever_name
from name import whatever_thing as whatever_name
from name import *

In [1]:
import numpy as np


In [ ]:
lists:
    - дуже повільні
    - довільні типи даних
np.array:
    - швидкі!
    - фіксовані типи змінних



In [2]:
list1 = [1,2,3]
list2 = [4,5,6]
list1*list2

TypeError: can't multiply sequence by non-int of type 'list'

In [3]:
list1 = np.array([1,2,3])
list2 = np.array([4,5,6])
list1*list2

array([ 4, 10, 18])

In [14]:
a = np.array([1,2,3])

In [25]:
b = np.array([[1.0,2.0,3.0],[4.0,5.0,6.0]])
b

array([[1., 2., 3.],
       [4., 5., 6.]])

In [16]:
b.ndim

2

In [26]:
b.shape

(2, 3)

In [57]:
a = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [34]:
# Get element [row, column]
a[1,3]

9

In [42]:
a[:,1]

array([2, 7])

In [46]:
# [row, start_index:end_index:step_size]
a[0, 1::2]

array([7, 9])

In [50]:
a[1,4] = 141
print(a)

[[  1   2   3   4   5]
 [  6   7   8   9 141]]


In [56]:
a[:,3] = 5
print(a)

[[1 2 3 5 5]
 [5 5 5 5 5]]


In [5]:
import math

In [6]:
x = math.ceil(4.3333)

In [8]:
from math import *

x = ceil(4.333)
x

5

In [10]:
y = math.floor(4.999)
print(y)

4


In [13]:
a = math.comb(10,6)
print(a)

210


In [14]:
a = math.perm(10,6)
print(a)

151200


In [15]:
a = math.fabs(-0.11)
print(a)

0.11


In [16]:
a = math.factorial(5)
print(a)

120


In [18]:
list_ = [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2]
x = sum(list_)
print(x)

1.9999999999999998


In [19]:
0.2+0.2+0.2+0.2+0.2+0.2+0.2+0.2+0.2+0.2

1.9999999999999998

In [20]:
y = math.fsum(list_)
print(y)

2.0


In [24]:
import statistics as st
x = st.mean([1,2,3,4,5,6])
x

3.5

In [42]:
import random

list_ = []
for i in range(10):
    a = random.randint(1, 100)
    list_.append(a)
list_

[66, 5, 9, 53, 98, 6, 58, 28, 90, 38]